@startuml
skinparam shadowing true

object Game {
}

object Player {
}

object CardBundle {
}

object Suit {
}

object Card {
    value
}

CardBundle -- "0..*"  Card : cards
Card --> "1"  Suit : suit

Game --> "1" CardBundle : deck
Game --> "1" Player : sam
Game --> "1" Player : dealer
Game --> "0..1" Player : winner
Player --> "1" CardBundle : hand

@enduml
