@startuml
skinparam shadowing true

object Result {
}

object Player {
}

object CardBundle {
}

enum Suit {
}

object Card {
    value
}

Game - Result : creates

CardBundle -- "0..*"  Card : cards
Card --> "1"  Suit : suit

Result --> "1" CardBundle : deck
Result --> "1" Player : sam
Result --> "1" Player : dealer
Result --> "0..1" Player : winner
Player --> "1" CardBundle : hand

@enduml
