@startuml

 activate Main
Main -> CardBundle : parse
activate CardBundle

alt if file is provided
    CardBundle -> Card : cardFromValue
    activate Card
    Card --> CardBundle
    deactivate Card
    CardBundle --> Main
else file not provided
    deactivate CardBundle
    Main -> CardBundle : shuffledDeck
    activate CardBundle
    CardBundle --> Main
    deactivate CardBundle
end


group#Khaki game loop

Main -> Game : playGame
activate Game

Game -> Player: draw(Card)
note right: adds a card to \nplayers hand
activate Player
Game <- Player
deactivate Player

Game -> Player: isBust
note right: true if sum points\nis over 21
activate Player
Game <- Player
deactivate Player

Game -> Player: hasBlackjack
note right: true if sum points \nis 21
activate Player
Game <- Player
deactivate Player

Game -> Player: sumValue
note right: Returns the total \npoints of card \nin hand
activate Player
Game <- Player
deactivate Player

Game --> Main: Result

end group

@enduml